version: '3'
services:
  client:
    container_name: debug_dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  server:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code
    # container_name: debug_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=london
      - PGDATABASE=library
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    image: postgres:12.4
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
    container_name: debug_dev_db
    # volumes:
    #   - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=library
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=london
volumes:
  dbdata:
networks: 
  default:
    name: debug_api
    
